package main

// DO NOT EDIT, this file is generated by hover at compile-time for the goImage plugin.

import (
	flutter "github.com/go-flutter-desktop/go-flutter"
	goImage "github.com/itMicmouse/goImage/go"
)

func init() {
	// Only the init function can be tweaked by plugin maker.
	options = append(options, flutter.AddPlugin(&goImage.GoImagePlugin{}))
}
